### ISSUE TITLE
User not found, sign up option

### ISSUE THREAD

**Issue by yogeswari05** [maniyaom/Movie-Ticket-Booking#44]
If user with given email id is not there, it would be better to show error as please sign up, no account found with this email id.
![image](https://github.com/user-attachments/assets/874fe94d-8674-434a-81bd-53bc2f7ad190)

**Comment by maniyaom** [comment]
@yogeswari05 It's generally better practice to use a more generic message, such as "Invalid username or password," rather than specifying whether the username is not registered. This approach helps enhance security by preventing attackers from determining which usernames exist in your system. By keeping the response vague, you reduce the risk of account enumeration attacks, where someone might try to identify valid usernames by observing error messages.
